Practical Classwork: Numerical and Categorical Data Using the Tips Dataset
We will use Seaborn’s built-in tips dataset to practice identifying numerical, categorical, discrete, continuous, nominal, and ordinal data. Because classifying columns by their meaning is more useful than blindly trusting their data types, this exercise includes both inspection and interpretation.

Complete the following tasks using Python, Pandas, and Seaborn.

1. Load the Tips dataset into a DataFrame.

In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
df= tips= sns.load_dataset('tips')

In [3]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

2. Display the first five rows.

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

3. Check the data types of all columns using df.dtypes.

In [5]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

4. Filter customers whose total_bill is greater than 20.

In [6]:
df.total_bill>=20

0      False
1      False
2       True
3       True
4       True
       ...
239     True
240     True
241     True
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

5. Explain why size is numerical but day is categorical.

Answer:----
1. Size (Numerical): Size is numerical because it can be measured or represented using numbers, such as 10, 20, or 30.
2. Day (Categorical): Day is categorical because it represents categories or names, such as Monday, Tuesday, or Wednesday, rather than a numerical quantity.