
Topics-----

1.Categorical Encoding

2.Transformers 

3.Missing Values

---> Encodering

A. Label Encoding (Labels to numbers)

B. Ordinal Encoding (Ordered categories to numbers)

C. One-Hot Encoding (Categories to separate columns)

----> Data

A. Ordinal Data ----> Which have some order to convert ordinal kata into number we use label encoder.

B. Numerical Data----> Which have numbers.

Label Encoder

---> Label Encoding converts categorical values into integer labels, mainly for representing categories numerically. the assigned numbers do not necessarily represent any meaningful order.

In [8]:
import pandas as pd 
import seaborn as sns

In [9]:
df= sns.load_dataset('tips')

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder_time= LabelEncoder()
encoded_data= encoder_time.fit_transform(df['time'])

In [ ]:
encoded_data

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
print("classes", encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [ ]:
for category, number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category, "--------", number)

Dinner -------- 0
Lunch -------- 1

In [ ]:
encoder_day= LabelEncoder()

encoded_day_data= encoder_day.fit_transform(df['day'])

In [ ]:
print("classes", encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [ ]:
for category, number in zip (encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category, "--------", number)

Fri -------- 0
Sat -------- 1
Sun -------- 2
Thur -------- 3

In [ ]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

One-Hot Encoder

---> One-Hot Encoding converts a categorical feature into multiple binary (0/1) columns, with one column for each category.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(sparse_output=False)

ohe.fit_transform(df[['sex','smoker',]])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [ ]:
ohe=OneHotEncoder(sparse_output=False, drop='first')

ohe_encoder=ohe.fit_transform(df[['sex','smoker',]])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [ ]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [ ]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

Function Transformer

---->FunctionTransformer is a scikit-learn transformer that allows you to apply a custom Python function to input features while keeping that transformation compatible with the scikit-learn Transformer API.

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
log=FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [ ]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

Power Transformer

In [ ]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

X = np.array([
    [-1],
    [0],
    [3],[5],[10],[50]
])
pt= PowerTransformer(method="yeo-johnson")

X_transformed = pt.fit_transform(X)

print('original')
print(X.ravel())

print('\nTransformed:')
print(np.round(X_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

original
[-1  0  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [ ]:
Y = np.array([
    [1],
    [1],
    [3],[5],[10],[50]
])
pt= PowerTransformer(method="box-cox")

Y_transformed = pt.fit_transform(Y)

print('original')
print(Y.ravel())

print('\nTransformed:')
print(np.round(X_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

original
[ 1  1  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[-0.23784507]

Missing-Value Strategies

---> Missing values are values that are not present in a dataset. They are usually represented as NaN, None, or blank values.

In [ ]:
import numpy as np
import pandas as pd

# Creating a sample dataset
data = {
    "Name": [
        "Aarav",
        "Priya",
        "Rohan",
        "Sneha",
        "Vikram",
        "Ananya",
        "Karan",
        "Pooja",
        "Rahul",
        "Neha",
    ],
    "Age": [25, np.nan, 30, 22, np.nan, 28, 35, np.nan, 40, 29],  # Numerical
    "Salary": [
        50000,
        64000,
        np.nan,
        45000,
        80000,
        np.nan,
        95000,
        52000,
        np.nan,
        61000,
    ],  # Numerical
    "Experience_Years": [
        2,
        np.nan,
        5,
        1,
        8,
        3,
        np.nan,
        2,
        12,
        4,
    ],  # Numerical
    "Department": [
        "IT",
        "HR",
        "IT",
        np.nan,
        "Finance",
        "Marketing",
        "Finance",
        np.nan,
        "IT",
        "HR",
    ],  # Categorical
    "City": [
        "Mumbai",
        "Pune",
        np.nan,
        "Delhi",
        "Mumbai",
        np.nan,
        "Bangalore",
        "Pune",
        "Delhi",
        "Mumbai",
    ],  # Categorical
    "Purchased": [
        "No",
        "Yes",
        "Yes",
        "No",
        np.nan,
        "Yes",
        "No",
        "Yes",
        "No",
        np.nan,
    ],  # Categorical
}

df = pd.DataFrame(data)

# Display data
display(df)

# Check missing values count per column
print("\nMissing values per column:")
print(df.isnull().sum())

# Check data types and non-null counts
print("\nData info:")
df.info()

     Name   Age   Salary  Experience_Years Department       City Purchased
0   Aarav  25.0  50000.0               2.0         IT     Mumbai        No
1   Priya   NaN  64000.0               NaN         HR       Pune       Yes
2   Rohan  30.0      NaN               5.0         IT        NaN       Yes
3   Sneha  22.0  45000.0               1.0        NaN      Delhi        No
4  Vikram   NaN  80000.0               8.0    Finance     Mumbai       NaN
5  Ananya  28.0      NaN               3.0  Marketing        NaN       Yes
6   Karan  35.0  95000.0               NaN    Finance  Bangalore        No
7   Pooja   NaN  52000.0               2.0        NaN       Pune       Yes
8   Rahul  40.0      NaN              12.0         IT      Delhi        No
9    Neha  29.0  61000.0               4.0         HR     Mumbai       NaN

Missing values per column:
Name                0
Age                 3
Salary              3
Experience_Years    2
Department          2
City                2
Purchased           2
dtype: int64

Data info:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              10 non-null     str
 1   Age               7 non-null      float64
 2   Salary            7 non-null      float64
 3   Experience_Years  8 non-null      float64
 4   Department        8 non-null      str
 5   City              8 non-null      str
 6   Purchased         8 non-null      str
dtypes: float64(3), str(4)
memory usage: 692.0 bytes

In [ ]:
from sklearn.impute import SimpleImputer

1. Mean Imputation

In [ ]:
imputer= SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.        ],
       [64000.        ],
       [63857.14285714],
       [45000.        ],
       [80000.        ],
       [63857.14285714],
       [95000.        ],
       [52000.        ],
       [63857.14285714],
       [61000.        ]])

In [ ]:
imputer= SimpleImputer(strategy='mean')
df['new_salary']= imputer.fit_transform(df[['Salary']]).flatten()

In [ ]:
df

,Name,Age,Salary,Experience_Years,Department,City,Purchased,new_salary
0,Aarav,25.0,50000.0,2.0,IT,Mumbai,No,50000.000000
1,Priya,NaN,64000.0,NaN,HR,Pune,Yes,64000.000000
2,Rohan,30.0,NaN,5.0,IT,NaN,Yes,63857.142857
3,Sneha,22.0,45000.0,1.0,NaN,Delhi,No,45000.000000
4,Vikram,NaN,80000.0,8.0,Finance,Mumbai,NaN,80000.000000
5,Ananya,28.0,NaN,3.0,Marketing,NaN,Yes,63857.142857
6,Karan,35.0,95000.0,NaN,Finance,Bangalore,No,95000.000000
7,Pooja,NaN,52000.0,2.0,NaN,Pune,Yes,52000.000000
8,Rahul,40.0,NaN,12.0,IT,Delhi,No,63857.142857
9,Neha,29.0,61000.0,4.0,HR,Mumbai,NaN,61000.000000

2. Median Imputation

In [ ]:
imputer= SimpleImputer(strategy='median')
df['new_Experience_Years']= imputer.fit_transform(df[['Experience_Years']]).flatten()

In [ ]:
df

,Name,Age,Salary,Experience_Years,Department,City,Purchased,new_salary,new_Experience_Years
0,Aarav,25.0,50000.0,2.0,IT,Mumbai,No,50000.000000,2.000
1,Priya,NaN,64000.0,NaN,HR,Pune,Yes,64000.000000,4.625
2,Rohan,30.0,NaN,5.0,IT,NaN,Yes,63857.142857,5.000
3,Sneha,22.0,45000.0,1.0,NaN,Delhi,No,45000.000000,1.000
4,Vikram,NaN,80000.0,8.0,Finance,Mumbai,NaN,80000.000000,8.000
5,Ananya,28.0,NaN,3.0,Marketing,NaN,Yes,63857.142857,3.000
6,Karan,35.0,95000.0,NaN,Finance,Bangalore,No,95000.000000,4.625
7,Pooja,NaN,52000.0,2.0,NaN,Pune,Yes,52000.000000,2.000
8,Rahul,40.0,NaN,12.0,IT,Delhi,No,63857.142857,12.000
9,Neha,29.0,61000.0,4.0,HR,Mumbai,NaN,61000.000000,4.000

3. Mode Imputation

In [ ]:
imputer= SimpleImputer(strategy='most_frequent')
df['City']= imputer.fit_transform(df[['City']]).flatten()

In [ ]:
df

,Name,Age,Salary,Experience_Years,Department,City,Purchased,new_salary,new_Experience_Years
0,Aarav,25.0,50000.0,2.0,IT,Mumbai,No,50000.000000,2.000
1,Priya,NaN,64000.0,NaN,HR,Pune,Yes,64000.000000,4.625
2,Rohan,30.0,NaN,5.0,IT,Mumbai,Yes,63857.142857,5.000
3,Sneha,22.0,45000.0,1.0,NaN,Delhi,No,45000.000000,1.000
4,Vikram,NaN,80000.0,8.0,Finance,Mumbai,NaN,80000.000000,8.000
5,Ananya,28.0,NaN,3.0,Marketing,Mumbai,Yes,63857.142857,3.000
6,Karan,35.0,95000.0,NaN,Finance,Bangalore,No,95000.000000,4.625
7,Pooja,NaN,52000.0,2.0,NaN,Pune,Yes,52000.000000,2.000
8,Rahul,40.0,NaN,12.0,IT,Delhi,No,63857.142857,12.000
9,Neha,29.0,61000.0,4.0,HR,Mumbai,NaN,61000.000000,4.000