EDA Foundations + Dataset Understanding

1.rows/columns/features/target

2.numerical, categorical, ordinal data

In [1]:
import pandas as pd

data = {
    'Age': [22, 25, 28, 30, 24, 35, 27, 32, 26, 29],
    'Salary': [25000, 35000, 45000, 55000, 30000,
               70000, 40000, 60000, 32000, 50000],
    'Experience': [1, 3, 5, 7, 2, 10, 4, 8, 2, 6],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male',
               'Male', 'Female', 'Male', 'Female', 'Male'],
    'Department': ['IT', 'HR', 'AI/ML', 'Finance', 'IT',
                   'AI/ML', 'HR', 'IT', 'Finance', 'AI/ML'],
    'City': ['Bhopal', 'Indore', 'Delhi', 'Mumbai', 'Bhopal',
             'Pune', 'Indore', 'Delhi', 'Mumbai', 'Pune']
}

df = pd.DataFrame(data)

print(df)

   Age  Salary  Experience  Gender Department    City
0   22   25000           1    Male         IT  Bhopal
1   25   35000           3  Female         HR  Indore
2   28   45000           5    Male      AI/ML   Delhi
3   30   55000           7  Female    Finance  Mumbai
4   24   30000           2    Male         IT  Bhopal
5   35   70000          10    Male      AI/ML    Pune
6   27   40000           4  Female         HR  Indore
7   32   60000           8    Male         IT   Delhi
8   26   32000           2  Female    Finance  Mumbai
9   29   50000           6    Male      AI/ML    Pune

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         10 non-null     int64
 1   Salary      10 non-null     int64
 2   Experience  10 non-null     int64
 3   Gender      10 non-null     str
 4   Department  10 non-null     str
 5   City        10 non-null     str
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [3]:
df.shape

(10, 6)

In [4]:
df['Age']

0    22
1    25
2    28
3    30
4    24
5    35
6    27
7    32
8    26
9    29
Name: Age, dtype: int64

In [5]:
for i in df ['Age']:
  print(i)

22
25
28
30
24
35
27
32
26
29

In [6]:
df[['Age','Gender']]

   Age  Gender
0   22    Male
1   25  Female
2   28    Male
3   30  Female
4   24    Male
5   35    Male
6   27  Female
7   32    Male
8   26  Female
9   29    Male

In [7]:
df.select_dtypes(exclude='object')

   Age  Salary  Experience
0   22   25000           1
1   25   35000           3
2   28   45000           5
3   30   55000           7
4   24   30000           2
5   35   70000          10
6   27   40000           4
7   32   60000           8
8   26   32000           2
9   29   50000           6

In [8]:
df.select_dtypes(include='object')

C:\Users\Abhij\AppData\Local\Temp\ipykernel_19696\676392701.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')

   Gender Department    City
0    Male         IT  Bhopal
1  Female         HR  Indore
2    Male      AI/ML   Delhi
3  Female    Finance  Mumbai
4    Male         IT  Bhopal
5    Male      AI/ML    Pune
6  Female         HR  Indore
7    Male         IT   Delhi
8  Female    Finance  Mumbai
9    Male      AI/ML    Pune

In [9]:
df.columns

Index(['Age', 'Salary', 'Experience', 'Gender', 'Department', 'City'], dtype='str')

In [10]:
df.select_dtypes(exclude='object').columns

Index(['Age', 'Salary', 'Experience'], dtype='str')

In [11]:
df.select_dtypes(include='object').columns

C:\Users\Abhij\AppData\Local\Temp\ipykernel_19696\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Gender', 'Department', 'City'], dtype='str')

In [12]:
df.loc[3]

Age                30
Salary          55000
Experience          7
Gender         Female
Department    Finance
City           Mumbai
Name: 3, dtype: object

In [13]:
df.loc[3,'City']

'Mumbai'

In [14]:
df.loc[[2,3,4]]

   Age  Salary  Experience  Gender Department    City
2   28   45000           5    Male      AI/ML   Delhi
3   30   55000           7  Female    Finance  Mumbai
4   24   30000           2    Male         IT  Bhopal

In [15]:
df.loc[[2,3,4],['Age','City']]

   Age    City
2   28   Delhi
3   30  Mumbai
4   24  Bhopal

In [16]:
df.iloc[[2,3,4],[0,1,2]]

   Age  Salary  Experience
2   28   45000           5
3   30   55000           7
4   24   30000           2

In [17]:
df.idxmax(axis=0)#Return index of first occurrence of maximum over requested axis.NA/null values are excluded.

Age           5
Salary        5
Experience    5
Gender        0
Department    0
City          5
dtype: int64

In [18]:
df.groupby('Department')['Salary'].mean()

Department
AI/ML      55000.000000
Finance    43500.000000
HR         37500.000000
IT         38333.333333
Name: Salary, dtype: float64

In [19]:
df.groupby('Gender')['Salary'].agg(["max","min"])

          max    min
Gender
Female  55000  32000
Male    70000  25000

In [20]:
df.columns

Index(['Age', 'Salary', 'Experience', 'Gender', 'Department', 'City'], dtype='str')

In [21]:
x=df[['Age', 'Salary', 'Experience', 'Gender', 'Department', 'City']] # independent variable
y=df['Salary'] # Dependent variable